from enum import IntEnum, unique

@unique
class Msg_type(IntEnum):
    NEW_EVENT=0
    INITIALIZED=1
    UPDATE_ESTIMATE=2
    STATUS=3
    UPDATE_WEATHER=4
    DELETE_EVENT=5
    UPDATE_USER_LOCATION=6
    REQUEST_ESTIMATE=7
    RESPONSE_ESTIMATE=8
    WEATHER_NOTIFICATION=9

    CURR_WEATHER=10 # for demo


